#!/usr/bin/env python3

##
## EPITECH PROJECT, 2019
## groundhog
## File description:
## groundhog python<
##

import sys
from math import *

def checkArgs(a, b):
    if (not a.isdigit() or not b.isdigit()):
        sys.stderr.write("Error: a and b parameters need to be integers.\n")
        sys.exit(84)

if (len(sys.argv) == 2 and sys.argv[1] == "-h"):
    print("USAGE")
    print("    ./203hotline [n k | d]")
    print("\nDESCRIPTION")
    print("    n\t   value for the computation of C(n, k)")
    print("    k\t   value for the computation of C(n, k)")
    print("    d\t   average duration of calls (in seconds)")
    sys.exit(0)

if (len(sys.argv) == 2 or len(sys.argv) == 3):
    
    sys.exit(0)
sys.exit(84)