#!/usr/bin/env python3

##
## EPITECH PROJECT, 2019
## groundhog
## File description:
## groundhog python<
##

import sys
import numbers
from math import *

def temperatureAverage(tab, period):
    if len(tab) <= period:
        return
    else:
        valueG = 0
        tempA = len(tab) - period
        while (tempA < len(tab)):
            d = tab[tempA] - tab[tempA - 1]
            valueG += (d if d > 0 else 0)
            tempA += 1
        valueG /= period
        return valueG

def temperatureEvolution(tab, period):
    if len(tab) <= period:
        return
    else:
        minim = tab[len(tab) - 1 - period]
        maxim = tab[len(tab) - 1]
        pourc = (maxim - minim) * 100 / minim
        if (pourc - floor(pourc) >= 0.5):
            return ceil(pourc)
        return floor(pourc)

def standardDeviation(tab, period):
    if len(tab) <= period:
        return
    else:
        valueG = 0
        tempA = len(tab) - period
        while (tempA < len(tab)):
            d = tab[tempA] - tab[tempA - 1]
            valueG += (d if d > 0 else 0)
            tempA += 1
        valueG /= period
        return valueG

def printResults(tempA, tempB, tempC):
    (print("g=%.2f" % tempA, end="    ") if tempA != None else print("g=nan", end="    "))
    (print("r=%i%%" % tempB, end="    ") if tempB != None else print("r=nan%", end="    "))
    (print("s=%.2f" % tempC) if tempC != None else print("s=nan"))

def relTempEvol(tab, period):
    tempA = temperatureAverage(tab, period)
    tempB = temperatureEvolution(tab, period)
    tempC = standardDeviation(tab, period)
    printResults(tempA, tempB, tempC)

def previson(tab, txt, period):
    tab.append(float(txt))
    relTempEvol(tab, period)

def loop(period):
    tab = []
    while (1):
        txt = input()
        if (txt == "STOP"):
            break
        elif (isFloat(txt)):
            previson(tab, txt, period)
        else:
            print("Bad input !!!")

def isFloat(value):
    try:
        float(value)
        return True
    except ValueError:
        return False

def checkArgs(a):
    if (not a.isdigit()):
        sys.stderr.write("Error: period need to be integers.\n")
        sys.exit(84)

def help():
    print("SYNOPSIS")
    print("    ./groundhog period")
    print("\nDESCRIPTION")
    print("    period\t   the number of days defining a period")
    sys.exit(0)

def main():
    if (len(sys.argv) == 2 and sys.argv[1] == "-h"):
        help()
    if (len(sys.argv) == 2):
        checkArgs(sys.argv[1])
        loop(int(sys.argv[1]))
        sys.exit(0)
    sys.exit(84)

if __name__  == "__main__":
    main()
